FROM node:22-slim
WORKDIR /src

RUN set -eux && \
    apt-get update -qq && \
    apt-get install -y \
      fonts-ipafont-gothic fonts-wqy-zenhei \
      fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      libxss1 libgtk2.0-0 libnss3 libatk-bridge2.0-0 libdrm2 \
      libxkbcommon0 libgbm1 libasound2 \
      chromium --no-install-recommends

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
CMD ["tail", "-f", "/dev/null"]